Site/ViewModels/Groups/CrudGroupViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;

namespace NeuroCloud.UI.Site.ViewModels.Groups
{
    public class CrudGroupViewModel
    {
	    public CrudGroupViewModel()
	    {
    		this.MenuList = new List<KeyValueViewModel<long>>();
			this.MenuIds = new List<GroupMenuViewModel>();
	    }

        public long Id { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }

	    public IList<KeyValueViewModel<long>> MenuList { get; set; }

        public IList<GroupMenuViewModel> MenuIds { get; set; }
    }
}

Site/ViewModels/Groups/ListGroupsViewModel.cs
namespace NeuroCloud.UI.Site.ViewModels.Groups
{
    public class ListGroupsViewModel
    {
        public long Id { get; set; }

        public string Name { get; set; }

        public int Page { get; set; }
    }
}

Site/ViewModels/Groups/SearchGroupsResultsViewModel.cs
using System;

namespace NeuroCloud.UI.Site.ViewModels.Groups
{
    public class SearchGroupsResultsViewModel
    {
        public Int64 Id { get; set; }
        public string Description { get; set; }
    }
}

Site/Controllers/GruposController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Iesi.Collections.Generic;
using NeuroCloud.Application;
using NeuroCloud.Application.SearchServices;
using NeuroCloud.Domain.Entities;
using NeuroCloud.Domain.Enums;
using NeuroCloud.Domain.QueryObjects;
using NeuroCloud.UI.Site.ViewModels;
using NeuroCloud.UI.Site.ViewModels.Groups;
using NHibernate.Mapping;
using GroupMenu = NeuroCloud.Domain.Entities.GroupMenu;

namespace NeuroCloud.UI.Site.Controllers
{
	public class GruposController : BaseController
	{
		private ISearchGroupsService SearchGroupsService { get; set; }
		private IGroupCrudService GroupCrudService { get; set; }
		private ISearchMenusService SearchMenusService { get; set; }

		public GruposController(ISearchGroupsService searchGroupsService, IGroupCrudService groupCrudService, ISearchMenusService searchMenusService)
		{
			this.SearchGroupsService = searchGroupsService;
			this.GroupCrudService = groupCrudService;
			this.SearchMenusService = searchMenusService;
		}

		[HttpGet , OutputCache(Duration = 1, NoStore = true)]
		public ActionResult Index()
		{
            return View("ListGroups");
		}

        [HttpGet, OutputCache(Duration = 1, NoStore = true)]
        public JsonResult PesquisarGrupos(ListGroupsViewModel viewModel)
        {
            var queryObject = new SearchUserQueryObject
            {
                Name = viewModel.Name,
                CurrentPage = viewModel.Page
            };

            var result = this.SearchGroupsService.SearchGroups(queryObject);

            var viewModelResult =
                result.Select(x => new SearchGroupsResultsViewModel
                {
                    Id = x.Id,
                    Description = x.Description
                }).ToArray();

            ViewData["QueryObject"] = queryObject;

            return Json(new
            {
                SearchResult = RenderPartialView(this, "_SearchGroupsResult", viewModelResult),
                Pager = RenderPartialView(this, "_Pager", queryObject)
            }, JsonRequestBehavior.AllowGet);
        }

		[HttpGet, OutputCache(Duration = 1, NoStore = true)]
		public ActionResult EditarGrupo(long id)
		{
			var group = this.SearchGroupsService.GetById(id);
			var viewModel = new CrudGroupViewModel
								{
									Id = group.Id,
									Description = group.Description,
									Status = (int)group.Status
								};

			var menus = this.SearchMenusService.GetAll();

            foreach (var menu in menus)
                viewModel.MenuList.Add(new KeyValueViewModel<long> { Value = menu.Description, Id = menu.Id });

		    foreach (var groupMenu in group.Menus)
		    {
		        viewModel.MenuIds.Add(new GroupMenuViewModel
		        {
		            MenuId = groupMenu.Menu.Id,
		            MenuDescription = groupMenu.Menu.Description,
		            IsChecked = groupMenu.Status == Status.Active
		        });
		    }
            
			return View("CrudGroup", viewModel);
		}

		[HttpGet, OutputCache(Duration = 1, NoStore = true)]
		public ActionResult Novo()
		{
			var viewModel = new CrudGroupViewModel();
			var menus = this.SearchMenusService.GetAll();

		    foreach (var menu in menus)
		        viewModel.MenuList.Add(new KeyValueViewModel<long> {Value = menu.Description, Id = menu.Id});

			return View("CrudGroup", viewModel);
		}

		[HttpPost, OutputCache(Duration = 1, NoStore = true)]
		public JsonResult NovoGrupo(CrudGroupViewModel viewModel)
		{
			if (string.IsNullOrEmpty(viewModel.Description))
				return Json(new { Status = "Error", Message = "O campo descrição é de preenchimento obrigatório." }, JsonRequestBehavior.DenyGet);

			if (viewModel.Status == 0)
				return Json(new { Status = "Error", Message = "O campo descrição é de preenchimento obrigatório." }, JsonRequestBehavior.DenyGet);

			var group = new Group();
			group.Description = viewModel.Description;

			if (viewModel.Status > 0)
				group.Status = (Status)viewModel.Status;

			foreach (var menu in viewModel.MenuIds)
			{
				group.Menus.Add(new GroupMenu
				{
					Menu = new Menu { Id = menu.MenuId },
					Status = menu.IsChecked ? Status.Active : Status.Inactive
				});
			}

			var result = this.GroupCrudService.SaveNewGroup(group);

			if (result.Id > 0)
				return Json(new { Status = "Success", Message = "Grupo inserido com sucesso." }, JsonRequestBehavior.DenyGet);

			return Json(new { Status = "Error", Message = "Não foi possível cadastrar o novo grupo. Verfique os dados e tente novamente." }, JsonRequestBehavior.DenyGet);
		}

		[HttpPost, OutputCache(Duration = 1, NoStore = true)]
		public JsonResult SalvarGrupo(CrudGroupViewModel viewModel)
		{
			var entity = this.SearchGroupsService.GetById(viewModel.Id);
			var menus = this.SearchMenusService.GetAll();

			entity.Description = viewModel.Description;
			entity.Status = (Status)viewModel.Status;
			entity.Menus.Clear();

			foreach (var menu in viewModel.MenuIds)
			{
				var menuSelected = menus.FirstOrDefault(x => x.Id == menu.MenuId);

				entity.Menus.Add(new GroupMenu
					                 {
										 Menu = menuSelected,
						                 Group = entity,
						                 Status = menu.IsChecked ? Status.Active : Status.Inactive
					                 });
			}

			try
			{
				this.GroupCrudService.UpdateGroup(entity);
			}
			catch (Exception exception)
			{
				return Json(new { Status = "Error", Message = "Não foi possível atualizar o novo grupo. Verfique os dados e tente novamente." }, JsonRequestBehavior.DenyGet);
			}

			return Json(new { Status = "Success", Message = "Grupo atualizado com sucesso." }, JsonRequestBehavior.DenyGet);
		}

        [HttpGet, OutputCache(Duration = 1, NoStore = true)]
        public JsonResult ExcluirGrupo(long id)
        {
            Group groupEntity = null;

            try
            {
                groupEntity = this.SearchGroupsService.GetById(id);
                this.GroupCrudService.InactivateGroup(groupEntity);
            }
            catch (InvalidOperationException invalidOperationException)
            {
                return this.ErrorResult(invalidOperationException.Message, JsonRequestBehavior.DenyGet);
            }

            if (groupEntity != null && groupEntity.Status == Status.Inactive)
            {
                return Json(new { Status = "Success", Message = string.Format("Grupo '{0}' excluído com sucesso.", groupEntity.Description) }, JsonRequestBehavior.DenyGet);
            }

            return Json(new { Status = "Error", Message = string.Format("Ocorreu um erro ao excluir o grupo '{0}'.", groupEntity.Description) }, JsonRequestBehavior.DenyGet);    
        }
	}
}

Site/Views/Grupos/CrudGroup.cshtml
@model NeuroCloud.UI.Site.ViewModels.Groups.CrudGroupViewModel

@using NeuroCloud.Domain.Enums
@{
    ViewBag.Title = Model.Id == 0 ? "NeuroCloud - Grupos / Novo Grupo" : "NeuroCloud - Grupos / Editar Grupo";
    var action = Model.Id == 0 ? "NovoGrupo" : "SalvarGrupo";
}

@section scripts
{
    <script src="~/Content/JS/Groups/CrudGroup.js"></script>
}

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    @if (Model.Id > 0)
    {
        <h3 id="title">Editar Grupo</h3>

        <ul class="breadcrumb">
            <li><a href="@Url.Action("Index","Usuarios")">Inicial</a></li>
            <li><a href="@Url.Action("Index", "Grupos")">Listar Grupos</a></li>
            <li id="breadCrumb" class="active">Editar Grupo</li>
        </ul>
    }
    else
    {
        <h3 id="title">Novo Grupo</h3>

        <ul class="breadcrumb">
            <li><a href="@Url.Action("Index","Usuarios")">Inicial</a></li>
            <li><a href="@Url.Action("Index", "Grupos")">Listar Grupos</a></li>
            <li id="breadCrumb" class="active">Novo Grupo</li>
        </ul>    
    }

</div>

@using (Html.BeginForm(action, "Grupos", FormMethod.Post, new { id = "frmGroup" }))
{
    <input type="hidden" id="Id" name="Id" value="@Model.Id"/>
    
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <fieldset>
            <legend>Dados do Grupo</legend>

            <div class="row">
                <div class="col-xs-12 col-lg-12">
                    <div class="form-group">
                        <label for="Description" class="col-xs-4 col-sm-2 col-md-2 col-lg-1 control-label">Descrição</label>
                        <div class="col-xs-8 col-sm-4 col-md-3 col-lg-3">
                            <input type="text" class="form-control" id="Description" name="Description" placeholder="Nome" maxlength="50" value="@Model.Description">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Status" class="col-xs-4 col-sm-2 col-md-2 col-lg-1 control-label">Status</label>

                        <div class="col-xs-4 col-sm-2 col-md-2 col-lg-2">
                            @if (Model.Status == 0)
                            {
                                <select id="Status" name="Status" class="form-control">
                                    <option value="0" selected="selected">Selecione...</option>
                                    <option value="@((int)Status.Active)" >Ativo</option>
                                    <option value="@((int)Status.Inactive)">Inativo</option>
                                </select>    
                            }
                            else if (Model.Status == (int)Status.Active)
                            {
                                <select id="Status" name="Status" class="form-control">
                                    <option value="0">Selecione...</option>
                                    <option value="@((int)Status.Active)" selected="selected" >Ativo</option>
                                    <option value="@((int)Status.Inactive)">Inativo</option>
                                </select>
                            }
                            else
                            {
                                <select id="Status" name="Status" class="form-control">
                                    <option value="0">Selecione...</option>
                                    <option value="@((int)Status.Active)" >Ativo</option>
                                    <option value="@((int)Status.Inactive)"  selected="selected">Inativo</option>
                                </select>
                            }

                        </div>

                    </div>
                </div>
            </div>

        </fieldset>

        <br />

        <fieldset>
            <legend>Menus Disponíveis</legend>

            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label class="col-xs-4 col-sm-1 col-md-1 col-lg-1 control-label hidden-xs">Menu</label>
                        <div class="col-xs-8 col-sm-3 col-md-3 col-lg-3">
                            <select id="listMenus" class="form-control">
                                <option value="0">Selecione...</option>

                                @foreach (var group in Model.MenuList)
                                {
                                    if (Model.MenuIds.Count > 0 && Model.MenuIds.Count(x => x.MenuId == group.Id) > 0)
                                    {
                                    <option value="@group.Id" class="hidden" disabled="disabled">@group.Value</option>
                                    }
                                    else
                                    {
                                    <option value="@group.Id">@group.Value</option>
                                    }
                                }

                            </select>
                        </div>
                        <button id="btnAddMenu" type="button" class="btn btn-primary" style="margin-right: 10px;">+</button>
                    </div>
                </div>
            </div>
        </fieldset>
        
        <br />

        <fieldset>
            <legend>Acessos Liberados</legend>
            <div class="row">
                <div class="col-lg-4">
                    <table id="accessList" class="table table-hover relationTable">
                        <thead>
                            <tr>
                                <th>Menu</th>
                                <th>Status</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="hidden">
                                <td>
                                    <input type="hidden" value="" id="MenuId" name="MenuIds" />
                                    <span id="menuName"></span>
                                </td>
                                <td>
                                    <select id="Status" name="Status" class="form-control">
                                        <option value="0" selected="selected">Selecione...</option>
                                        <option value="@((int)Status.Active)" >Ativo</option>
                                        <option value="@((int)Status.Inactive)">Inativo</option>
                                    </select>
                                </td>
                                <td class="text-center">
                                    <button id="btnRemoveAccess" type="button" class="close" aria-hidden="true">&times;</button></td>
                            </tr>

                            @if (Model.Id > 0)
                            {
                                foreach (var menuGroup in Model.MenuIds)
                                {
                                <tr>
                                    <td>
                                        <input type="hidden" value="@menuGroup.MenuId" id="MenuId" name="MenuIds" />
                                        <span id="menuName">@menuGroup.MenuDescription</span>
                                    </td>
                                    <td>
                                        <select id="Status" name="Status" class="form-control">

                                            @if (menuGroup.IsChecked)
                                            {
                                                <option value="0">Selecione...</option>
                                                <option value="@((int)Status.Active)" selected="selected">Ativo</option>
                                                <option value="@((int)Status.Inactive)">Inativo</option>
                                            }
                                            else
                                            {
                                                <option value="0">Selecione...</option>
                                                <option value="@((int)Status.Active)">Ativo</option>
                                                <option value="@((int)Status.Inactive)" selected="selected">Inativo</option>
                                            }
                                        </select>
                                    </td>
                                    <td class="text-center">
                                        <button id="btnRemoveAccess" type="button" class="close" aria-hidden="true">&times;</button></td>
                                </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </fieldset>
    </div>
    
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <hr />

        <div id="crudActions">
            <button id="btnSave" type="button" class="btn btn-success" style="margin-right: 10px;">Salvar</button>
            <button id="btnDelete" type="button" class="btn btn-danger" style="margin-right: 10px;">Excluir</button>
            <button id="btnBack" type="button" class="btn btn-primary" style="margin-right: 10px;">Voltar</button>
        </div>
    </div>
}


Site/Views/Grupos/ListGroups.cshtml
@{
    ViewBag.Title = "NeuroCloud - Usuários / Listagem de Grupos";
}

@section scripts
{
    <script src="~/Content/JS/Groups/ListGroups.js"></script>
}

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <h3>Listagem de Grupos</h3>

    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Usuarios")">Inicial</a></li>
        <li class="active">Listar Grupos</li>
    </ul>
</div>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div id="searchTerms">
        <div class="row">
            <div class="form-group">
                <label for="Name" class="col-xs-2 col-sm-1 col-md-1 col-lg-1 control-label">Nome</label>
                <div class="col-xs-10 col-sm-3 col-md-4 col-lg-3">
                    <input type="text" class="form-control" id="Name" placeholder="Nome">
                </div>
                <div class="clearfix visible-xs">
                    &nbsp;
                </div>
                <div class="visible-xs col-xs-2"></div>
                <div class="col-xs-10 col-sm-3 col-md-2 col-lg-2 ">
                    <button id="btnSearch" type="button" class="btn btn-primary btn-block">Filtrar</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <hr />
</div>
<div id="paging-top-parent" class="">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
        <button id="btnNew" type="button" class="btn btn-primary">Inserir</button>
    </div>
    <div id="paging-top" class="col-xs-12 col-sm-6 col-md-6 col-lg-6 hidden-xs">
    </div>
</div>
<br class="hidden-xs" />
<div id="results">
</div>

<div id="paging-bottom-mobile" class="col-xs-12 visible-xs">
</div>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <hr />
</div>

<div id="paging-bottom-parent" class="">
    <div id="listActions" class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
        <button id="btnView" type="button" class="btn btn-primary disabled" style="margin-right: 10px;">Consultar</button>
        <button id="btnEdit" type="button" class="btn btn-primary disabled" style="margin-right: 10px;">Alterar</button>
        <button id="btnDelete" type="button" class="btn btn-danger disabled" style="margin-right: 10px;">Excluir</button>
    </div>

    <div id="paging-bottom" class="col-xs-12 col-sm-6 col-md-6 col-lg-6 hidden-xs">
    </div>

</div>

Site/Views/Grupos/_SearchGroupsResult.cshtml
@using NeuroCloud.Domain.QueryObjects
@model IList<NeuroCloud.UI.Site.ViewModels.Groups.SearchGroupsResultsViewModel>

<div class="row">&nbsp; &nbsp; </div>
<div id="searchResult" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
    @if (Model != null && Model.Any())
    {
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Nome</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td data-title="Nome">@Html.ActionLink(item.Description, "EditarGrupo", "Grupos", new {id = item.Id}, null)</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h4>Nenhum registro encontrado.</h4>
    }
</div>
